server:
  port: 8503
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 配置路由，注意这里是个列表，每一项都包含了很多信息
      routes:
      - id: interestcircle-service   # 路由名称
        uri: lb://interestcircleservice  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
        predicates: # 路由规则，断言什么请求会被路由
          - Path=/cityController/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务