server:
  port: 8201

spring:
  application:
    name: article-service
  elasticsearch:
    uris: http://127.0.0.1:9200


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka