package com.example.community.service.impl;
import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.example.community.entity.User;import com.example.community.mapper.UserMapper;import com.example.community.service.UserService;import lombok.RequiredArgsConstructor;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class UserServiceImpl implements UserService {private final UserMapper mapper;private final PasswordEncoder encoder;
public User get(Integer id){return required(id);}public IPage<User> search(String keyword,long page,long size){var q=new com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<User>();if(keyword!=null&&!keyword.isBlank()){q.like(User::getUsername,keyword);if(isInteger(keyword))q.or().eq(User::getUserId,Integer.valueOf(keyword));}return mapper.selectPage(new Page<>(page,size),q.orderByAsc(User::getUserId));}
public User login(Integer id,String password){User user=required(id);if(!encoder.matches(password,user.getPassword()))throw new IllegalArgumentException("账号或密码错误");return user;}
@Transactional public User create(User user){if(mapper.selectById(user.getUserId())!=null)throw new IllegalArgumentException("用户编号已存在");user.setPassword(encoder.encode(user.getPassword()));if(user.getUsertype()==null)user.setUsertype(false);mapper.insert(user);return required(user.getUserId());}
@Transactional public User update(Integer id,User input){User user=required(id);if(input.getUsername()!=null)user.setUsername(input.getUsername());if(input.getUsertype()!=null)user.setUsertype(input.getUsertype());if(input.getUserpic()!=null)user.setUserpic(input.getUserpic());mapper.updateById(user);return required(id);}
@Transactional public void changePassword(Integer id,String oldValue,String newValue){User user=login(id,oldValue);user.setPassword(encoder.encode(newValue));mapper.updateById(user);}@Transactional public void delete(Integer id){if(mapper.deleteById(id)==0)throw new IllegalArgumentException("用户不存在");}
private User required(Integer id){User v=mapper.selectById(id);if(v==null)throw new IllegalArgumentException("用户不存在");return v;}private static boolean isInteger(String s){try{Integer.parseInt(s);return true;}catch(Exception e){return false;}}}
